export { default as Footer } from "./Footer/Footer"
export { default as Header } from "./Header/Header"
export { default as MovieDetails } from "./MovieDetails/Details"
export { default as Profile } from "./Profile/Profile"
export { default as Dashboard } from "./Dashboard/Dashboard"
export { default as Search } from "./Search/Search"
export { default as Login } from "./Login/Login"
export { default as Register } from "./Register/Register"
